UserParameter=vrsctest.height,/home/verustest/bin/verustest -datadir=/home/verustest/.komodo/vrsctest getinfo | jq .blocks
UserParameter=vrsctest.hash,/home/verustest/bin/verustest -datadir=/home/verustest/.komodo/vrsctest getbestblockhash
UserParameter=vrsctest.connections,/home/verustest/bin/verustest -datadir=/home/verustest/.komodo/vrsctest getinfo | jq .connections
UserParameter=vrsctest.versioncheck,/etc/zabbix/zabbix_agentd.conf.d/verus_version_check.sh
UserParameter=vrsctest.version,/home/verustest/bin/verustest -datadir=/home/verustest/.komodo/vrsctest getinfo | jq .VRSCversion
UserParameter=vrsctest.running,/etc/zabbix/zabbix_agentd.conf.d/verustest_running.sh
